//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class moviesDBEntities : DbContext
    {
        public moviesDBEntities()
            : base("name=moviesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MovieInfo> MovieInfoes { get; set; }
    
        public virtual int sp_AddMovies(string movieName, string theatre, Nullable<decimal> rate)
        {
            var movieNameParameter = movieName != null ?
                new ObjectParameter("MovieName", movieName) :
                new ObjectParameter("MovieName", typeof(string));
    
            var theatreParameter = theatre != null ?
                new ObjectParameter("Theatre", theatre) :
                new ObjectParameter("Theatre", typeof(string));
    
            var rateParameter = rate.HasValue ?
                new ObjectParameter("Rate", rate) :
                new ObjectParameter("Rate", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AddMovies", movieNameParameter, theatreParameter, rateParameter);
        }
    
        public virtual ObjectResult<sp_Getmovies_Result> sp_Getmovies()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Getmovies_Result>("sp_Getmovies");
        }
    }
}
