//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBasedDemo1
{
    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;
    
    public partial class Departments
    {
        static String cs = @"Data source = .\SqlExpress; Initial Catalog = StudentDeptCor; Integrated Security = true";
      
        
        public Departments()
        {
            this.Courses = new HashSet<Courses>();
            this.StudentInfoes = new HashSet<StudentInfo>();
        }
    
        
        
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public int StudentInfoStudentID { get; set; }
    
        public virtual ICollection<Courses> Courses { get; set; }
        public virtual ICollection<StudentInfo> StudentInfoes { get; set; }

        public static void showDepartments()
        {
            SqlConnection con = new SqlConnection(cs);
            con.Open();

            Departments dep;

            SqlCommand cmd = new SqlCommand("spShowDepartments",con);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            SqlDataReader reader = cmd.ExecuteReader();

            while (reader.Read())
            {
                dep = new Departments();

                dep.DepartmentId = Convert.ToInt32(reader["DepartmentID".ToString()]);
                dep.DepartmentName = reader["DepartmentName"].ToString();

                Console.WriteLine("{0} \t {1}", dep.DepartmentId, dep.DepartmentName);
            }
            reader.Close();
            con.Close();

            
        }
    }
}
