//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBasedDemo1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        public StudentInfo()
        {
            this.Courses = new HashSet<Courses>();
        }
    
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int DepartmentsDepartmentId { get; set; }
        public int DepartmentsDepartmentId1 { get; set; }
    
        public virtual Departments Department { get; set; }
        public virtual ICollection<Courses> Courses { get; set; }
    }
}
