//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDemo1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeData
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public string Department { get; set; }
        public Nullable<int> EmpType { get; set; }
        public Nullable<int> HourlySal { get; set; }
        public Nullable<int> Bonusrate { get; set; }
    
        public virtual EmployeeType EmployeeType { get; set; }
    }
}
