//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDemo1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeType
    {
        public EmployeeType()
        {
            this.EmployeeDatas = new HashSet<EmployeeData>();
        }
    
        public int TypeID { get; set; }
        public string EmpType { get; set; }
    
        public virtual ICollection<EmployeeData> EmployeeDatas { get; set; }
    }
}
