//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MovieInfo
    {
        public int MovieID { get; set; }
        [Required]
        public string MovieName { get; set; }
        [Required]
        public string Theatre { get; set; }
        [Required]
        public Nullable<decimal> Rate { get; set; }
        [Required]
        public Nullable<System.DateTime> ReleaseDate { get; set; }
    }
}
