//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirstDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int ProjectID { get; set; }
        public int ManagerID { get; set; }
        public string ProjectNm { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual Manager Manager { get; set; }
    }
}
